openapi: 3.0.3
info:
  title: Backend Challenge
servers:
  - url: http://localhost:3000/
paths:
  /ships/summary:
    get:
      tags:
        - ships
      summary: Retrieve summary
      description: Retrieve summary of ships
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
        '401':
          description: Unauthorized
        '500':
          description: Error encountered
      security:
        - api_key: []
  /ships/{shipId}:
    get:
      tags:
        - ships
      summary: Retrieve ship by id
      description: Retrieve ship by id
      parameters:
        - name: shipId
          in: path
          description: ID of ship to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ship'
        '401':
          description: Unauthorized
        '500':
          description: Error encountered
      security:
        - api_key: []
  /ships/query:
    get:
      tags:
        - ships
      summary: Retrieve ships by query
      description: Retrieve ships by query
      parameters:
        - name: type
          in: query
          description: Type of ship to return
          schema:
            type: string
        - name: name
          in: query
          description: Name of ship to return
          schema:
            type: string
        - name: role
          in: query
          description: Role of ship to return
          schema:
            type: string
        - name: year_built_start
          in: query
          description: Range start for year built
          schema:
            type: integer
            format: int32
        - name: year_built_end
          in: query
          description: Range end for year build
          schema:
            type: integer
            format: int32
        - name: page
          in: query
          description: Page for pagination
          schema:
            type: integer
            format: int32
        - name: page_size
          in: query
          description: Page size for pagination
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                example: []
        '401':
          description: Unauthorized
        '500':
          description: Error encountered
      security:
        - api_key: []
components:
  schemas:
    Summary:
      type: object
      properties:
        total_ships:
          type: integer
          format: int32
          example: 0
        total_active_ships:
          type: integer
          format: int32
          example: 0
        total_inactive_ships:
          type: integer
          format: int32
          example: 0
        ship_types:
          type: object
          example: {}
        min_year_built:
          type: integer
          format: int32
          example: 1900
        max_year_built:
          type: integer
          format: int32
          example: 1900
    Ship:
      type: object
      properties:
        id:
          type: string
          example: ''
        name:
          type: string
          example: ''
        type:
          type: string
          example: ''
        year_built:
          type: integer
          format: int32
          example: 1900
        active:
          type: boolean
          example: false
        roles:
          type: array
          example: []
  securitySchemes:
    api_key:
      type: apiKey
      name: api-key
      in: header
